### ISSUE TITLE
Integrate package vignette?

### ISSUE THREAD

**Issue by ewallace** [kkdey/Logolas#11]
It would be extremely helpful to integrate a vignette to your Logolas R package to teach users how to get started. **How do I go from a character vector of sequences to a EDLogo?** What are the key functions? You have public code to do that in https://github.com/kkdey/Logolas-pages and https://github.com/kkdey/Logolas-paper, but it is very difficult from the outside to figure out where in there to find the relevant code.

Without this, I found it too hard to get started using your clever and sensible sequence logos.

There's some great advice on writing a vignette here:
http://r-pkgs.had.co.nz/vignettes.html

Thanks!
Edward

**Comment by kkdey** [comment]
Thanks Edward for your comments. did you take a look at our vignettes page? https://kkdey.github.io/Logolas-pages/workflow.html 

or you can look up the codes in the gallery to check how you can go from a matrix of composition of strings or characters to the EDLogo. https://kkdey.github.io/Logolas-pages/Gallery.html

If you have a character vector of sequences, all you would need to do is to get a matrix of counts of the symbols for each position of the sequence. For example, if the sequences are 

AAAC
ACTC
AGTC
ACCC

then you can create the matrix
            A    C   G   T
pos1    3     0   0   0
pos2    1     2    1   0
pos3    1     1    0   2
pos4    0    4    0   0

and this matrix would then become input to the `nlogomaker` for EDLogo and `logomaker` for standard logo plot visualization. 

Let me know if that helps.

Thanks.

Kushal

**Comment by ewallace** [comment]
Thanks Kushal for your helpful response. I confess that I had navigated to https://github.com/kkdey/Logolas-pages 
not
https://kkdey.github.io/Logolas-pages/

Now, the vignettes aren't accessible within the R package, only by web. Could you package an introduction to be called from vignette("Logolas")? 

How about having a vignette starting something like this?

```{r }
library(Logolas)
library(Biostrings)

# list of sequences
myseqs <- c("AAAC","ACTC","AGTC","ACCC","ATAC")
# calculate position frequency matrix (PFM)
myPFM <- consensusMatrix(myseqs)
# give PFM column names
colnames(myPFM) <- 1:4

myPFM

# define color profile
color_profile <- list("type" = "per_row",
"col" = RColorBrewer::brewer.pal(4,name ="Spectral"))

logomaker(myPFM,color_profile = color_profile, ic.scale = TRUE)

nlogomaker(myPFM,color_profile = color_profile)

```

I found that using consensusMatrix on the list of strings was easier to understand than your Lawn/Car/Mail example in ?logomaker

Thanks
Edward

**Comment by ewallace** [comment]
The new vignette is fantastic! Very helpful indeed.

Now, it would be helpful to make it discoverable from inside R by 
`browseVignettes("Logolas")`
and
`vignette("logomaker")`

Thanks 
Edward

**Comment by pcarbo** [comment]
@ewallace There is currently an error in one or more of the vignettes, so the package currently cannot be installed with the vignettes. As soon as this is fixed by @kkdey they should be discoverable within R.

**Comment by kkdey** [comment]
@ewallace The bug has been fixed and the `browseVignettes` should work now. Thanks so much for the feedback. I am closing the issue for now.
