### ISSUE TITLE
'logo_control_default' not found

### ISSUE THREAD

**Issue by ritma001** [kkdey/Logolas#14]
Hi there,

I am trying to create ED logo and I downloaded nucleotide sequences (shown below) from https://rdrr.io/bioc/Logolas/man/logomaker.html .

sequence <- c("CTATTGT", "CTCTTAT", "CTATTAA", "CTATTTA", "CTATTAT", 
              "CTTGAAT", "CTTAGAT", "CTATTAA", "CTATTTA", "CTATTAT",
              "CTTTTAT", "CTATAGT", "CTATTTT", "CTTATAT", "CTATATT", 
              "CTCATTT", "CTTATTT", "CAATAGT", "CATTTGA", "CTCTTAT", 
              "CTATTAT", "CTTTTAT", "CTATAAT", "CTTAGGT",
              "CTATTGT", "CTCATGT", "CTATAGT", "CTCGTTA", 
              "CTAGAAT", "CAATGGT")
`logomaker(sequence, type = "EDlogo")` however, did give me an error: 
"Error in logomaker(sequence, type = "EDlogo") : 
  object 'logo_control_default' not found".

I try to use some sequences as logo_control and bg but, the error persists.
And, I could not find this incident mentioned online.
Can you give me a clue to such problem?

**Comment by kkdey** [comment]
Hi,

I think the error is due to the fact that type should be "EDLogo" instead of "EDlogo",  try running this command

`logomaker (sequence, type = "EDLogo")`

I will place a condition in the function to safeguard against such syntax errors in future

**Comment by kkdey** [comment]
I have now added a check at the start of the `logomaker` function that can detect such syntax issues and give non-confusing error messages like the one you encountered. Hope this helps. 

Thanks

Kushal

**Comment by ritma001** [comment]
That is indeed the typo. Thanks for a quick response and a change regarding error messages.

Best,

Wannisa
