### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by agombolay** [kkdey/Logolas#16]
After running "install_github("kkdey/Logolas",build_vignettes = TRUE)", I get the following error: "Error: (converted from warning) package ‘ashr’ is not available (for R version 3.5.2)." I tried version 3.43 of R and that did not work either. What version of R should I use (I am using a Mac)?

**Comment by pcarbo** [comment]
@agombolay Thanks for letting us know about this issue---this is a temporary issue with the ashr package, not with Logolas. Please go [here](https://github.com/stephens999/ashr) to install the ashr package before installing Logolas. I will close this issue, but let us know if you are still having issues.

**Comment by agombolay** [comment]
When running "install_github("stephens999/ashr")", I got the following error:                                  clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘mixsqp’

**Comment by pcarbo** [comment]
@agombolay Can you please post your Issue on the ashr repository? Thanks.
