### ISSUE TITLE
Convergence issue

### ISSUE THREAD

**Issue by CDieterich** [kkdey/Logolas#19]
Great tool !

However, when I use:
logomaker(A, type = "EDLogo", bg=apply(m6A,2,function(x){x/sum(x)}))

I get..
Analyzing the positional frequency matrix
color_type not provided, so switching to per_row option for
            color_type
frame width not provided, taken to be 1
frame width not provided, taken to be 1
Warnmeldung:
In estimate_mixprop(data, g, prior, optmethod = optmethod, control = control,  :
  Optimization failed to converge. Results may be unreliable. Try increasing maxiter and rerunning.

Is there a way to change/pass this parameter ?

**Comment by kkdey** [comment]
@CDieterich 

The warning message comes from the ashr functionality that EDLogo uses for shrinkage. We have a recommend ash setting for EDLogo model and therefore, we did not offer the user control on tuning ash. However, this failure of convergence is not a big deal as the tolerance level of ash is very low, and EDLogo results usually change very little upon changing the maxiters and related controls on ash. I would suggest you can ignore this warning. Or you can use `shrink=FALSE` in logomaker if you so wish.

**Comment by CDieterich** [comment]
Thanks !
