### ISSUE TITLE
Unable to represent N-glycosylation using my data

### ISSUE THREAD

**Issue by MauriAndresMU1313** [kkdey/Logolas#21]
Hi! 

I tried to represent motif sequence, however, the EDplot not represent depletion amino acid letters how I expect. 
Here is my data (text file): 
`NSTE
NFSW
NFSW
NFSW
NFSW
NFSW
NFSW
NSTE
NFSW
NFSW
NFSW
NFSW
`
Then I use this line: 
`sequence <- c("NSTE","...")`
First, represent the data  with logomaker:
`logomaker(sequence,type = "Logo")`
This result in this plot: 
![1](https://user-images.githubusercontent.com/68199472/118525997-c905f200-b70d-11eb-867f-bfee25a234b3.png)
I expect that using EDlogo give me a deplete view of my data, however when I use this line: 
`> logomaker(sequence, type = "EDLogo")`
Result in this plot: 
![2](https://user-images.githubusercontent.com/68199472/118526023-d02d0000-b70d-11eb-968a-fa20f1057853.png)
I think that this is not the correct logo that represents Enriechmente Depletion or I´m wrong? (If this is the case, please correct me).
When I plot the second Logo, there are some warning messages that I can´t figure out what means exactly in this example. 
Here the messages: 
```

using a background with equal probability for all symbols
Analyzing the positional frequency matrix
color_type not provided, so switching to per_row option for
            color_type
using a background with equal probability for all symbols
frame width not provided, taken to be 1
frame width not provided, taken to be 1
Error in grid::unit(letters$x, "native") : 
  'x' and 'units' must have length > 0
Also: Warning messages: 
In if (class (table) == "data.frame") {:
   the condition has length> 1 and only the first element will be used
2: In if (class (table)! = "Matrix") {:
   the condition has length> 1 and only the first element will be used
3: In if (class (table) == "data.frame") {:
   the condition has length> 1 and only the first element will be used
4: In if (class (table)! = "Matrix") {:
   the condition has length> 1 and only the first element will be used 

```
I don´t understand the error and if this error influences the plot result. 

Any comment or help is welcome!

Thank!

**Comment by MauriAndresMU1313** [comment]
Another question: Is it necessary to provide a matrix to generate an ED plot? I think in my data and I only have provided a sequence (character). If this is the case, how can obtain a matrix for this class of data? Thank! @hpages @kkdey

**Comment by hpages** [comment]
@MauriAndresMU1313 I can't help sorry. I don't know anything about **Logolas**. The fact that I'm showing up as a contributor is only an artifact of me pushing automatic commits every 6 months to bump all Bioconductor package versions as part of the Bioconductor release process.

Best,
H.

**Comment by MauriAndresMU1313** [comment]
@hpages Oh sorry for that, I don´t know that. However, maybe you could help me in one way. Do you know if @kkdey is actually active in Github? Because looks that he connected last time in March. Do you know anything about him?

**Comment by kkdey** [comment]
@MauriAndresMU1313  Hi Mauri. Sorry for the delay in response. For the string logo plots, you cannot use the string format, because the string format will treat each character separately. You need to use it as a matrix. You can follow this example from the vignette: 

data(histone_marks)
logomaker(histone_marks$mat, bg = histone_marks$bgmat, type = "EDLogo")

Your input matrix here will the matrix of probabilties or counts of the individual strings that you see in your data.

**Comment by hpages** [comment]
FWIW questions about Bioconductor packages like **Logolas** can also be asked on the [Bioconductor support site](https://support.bioconductor.org/). All Bioconductor package maintainers should be registered there and receive notifications when questions are tagged with the name of their package.

**Comment by MauriAndresMU1313** [comment]
@kkdey I understand your point, however, how I can get the matrix for my data? I ask this because I extracted my data from a report of N-glycosylation, where the output say me where is the sequence around the glycosylation site. Then, I extracted this sequence, for example, NSTE NFSW NFSW .... but this is all my data. What do you think about that? Is there a way to obtain a matrix with only this NFSW NFSW...? Thank you!

**Comment by MauriAndresMU1313** [comment]
@hpages Thank you for the Bioconductor support site, I didn't know it exists. It´s great to know. Thank you again!

**Comment by kkdey** [comment]
@MauriAndresMU1313 You can just compute the number of times each string appears in your sequence per site, For example, if you have two sequences:
Site 1: NSTE NSTE NSFW NSTE NSFW NSTE
Site 2: NSTE NSFW NSFW NSFW NSFW NSFW

then the matrix would be like 
               Site 1. Site 2
NSTE.      4.         1
NSFW.      2.         5

**Comment by MauriAndresMU1313** [comment]
Oh great! This is so useful. I going to try your suggestion! Thank you!

**Comment by kkdey** [comment]
Thanks, just a small correction, the matrix should be the transpose of the matrix I wrote above.

**Comment by MauriAndresMU1313** [comment]
Hi again! I have a new question that I can´t figure out. Is it possible to set an EDlogo with the same color letter for each letter? For example,  I tried different ways with `colors` but the colors always change. I´m looking to set the same pattern of color to each letter, in this case, Amino acid sequence. @kkdey Thank!

**Comment by kkdey** [comment]
Hi Mauri,

You can try something along the lines of this example:

library(Logolas)
data(histone_marks)
logomaker(histone_marks$mat, bg=histone_marks$bgmat, type = "EDLogo",
          color_type = "per_symbol", color_seed = 700)

This may be similar to what you are looking for. You can try playing around with the seed to see which color palette works best. I recommend using color_seed instead of colors which is slightly more complex to handle.
